from django.db import models

# Create your models here.
class StudentData(models.Model) :
    studentID = models.CharField(max_length=100000) 
    Complete1 = models.IntegerField()
    CompleteCIP1  = models.IntegerField()
    CompleteDevEnglish = models.IntegerField()
    CompleteDevMath = models.IntegerField()
    CumGPA = models.DecimalField(max_digits=1000000, decimal_places=5)
    CumLoanAtEntry = models.DecimalField(max_digits=1000000, decimal_places=5)
    Dropout = models.IntegerField(blank=True)
    EngPlacement = models.IntegerField()
    EnrollmentStatus = models.IntegerField()
    FathersHighestGradeLevel = models.IntegerField()
    GatewayEnglishStatus = models.IntegerField()
    HSDip = models.IntegerField()
    HighDeg = models.IntegerField()
    Major1 = models.IntegerField()
    NumColCredAcceptTransfer = models.IntegerField()
    NumColCredAttemptTransfer = models.IntegerField()
    TermGPA = models.DecimalField(max_digits=1000000, decimal_places=5)
    TotalGrant  = models.DecimalField(max_digits=1000000, decimal_places=5)
    TotalScholarship  = models.DecimalField(max_digits=1000000, decimal_places=5)
    TotalLoan   = models.DecimalField(max_digits=1000000, decimal_places=5)
    TotalWorkStudy  = models.DecimalField(max_digits=1000000, decimal_places=5)