# Generated by Django 4.0.1 on 2022-01-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=100000)),
                ('Complete1', models.IntegerField()),
                ('CompleteCIP1', models.IntegerField()),
                ('CompleteDevEnglish', models.IntegerField()),
                ('CompleteDevMath', models.IntegerField()),
                ('CumGPA', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('CumLoanAtEntry', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('Dropout', models.IntegerField(blank=True)),
                ('EngPlacement', models.IntegerField()),
                ('EnrollmentStatus', models.IntegerField()),
                ('FathersHighestGradeLevel', models.IntegerField()),
                ('GatewayEnglishStatus', models.IntegerField()),
                ('HSDip', models.IntegerField()),
                ('HighDeg', models.IntegerField()),
                ('Major1', models.IntegerField()),
                ('NumColCredAcceptTransfer', models.IntegerField()),
                ('NumColCredAttemptTransfer', models.IntegerField()),
                ('TermGPA', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('TotalGrant', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('TotalScholarship', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('TotalLoan', models.DecimalField(decimal_places=5, max_digits=1000000)),
                ('TotalWorkStudy', models.DecimalField(decimal_places=5, max_digits=1000000)),
            ],
        ),
    ]
