# Generated by Django 4.0.1 on 2022-01-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentData',
            new_name='StudentDataDropout',
        ),
    ]
